version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "8000:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    environment:
      - SERVER.DEFAULT_LISTEN_ADDRESS=0.0.0.0
    entrypoint: ["ollama", "serve"]

volumes:
  ollama:
    driver: local

# docker exec -it ollama ollama run llama3

